apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ds-demo
  template:
    metadata:
      labels:
        app: ds-demo
    spec:
      containers:
        - name: ds-demo
          image: ds-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080